version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 87354250-ad3b-48f9-996b-bdb116633f3a
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
