version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: e23be5a0-3823-4ad4-b837-fba20c8d2d5d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
