version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 58d71e08-5a32-47a9-8cc6-59de997670ec
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
