version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 5f4d7ce3-0949-48ca-b63a-a63dc5c0c010
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
