version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 3205f308-f825-480a-96ef-5fbd41d8df82
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
