version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 5eb8fa30-4d5f-41ac-a732-fcb9a5a73f26
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
