version: 1.0
app:
  instances: 
    min: 1
    max: 1
  version: f9392c70-2092-46ed-a286-7a603f89f821
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
