version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: a3e651a5-5e5c-4c23-993e-4b3086b47a8f
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
