version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 2e467c86-7544-4e64-a54d-ea570e00aace
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
