version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: efb58d06-66ca-4545-ab52-6a33da96e173
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
