version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: a7693965-9b6e-4bd6-b291-9cbd9a121e65
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
