version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 2310ee26-8521-4161-b3cc-8546e726358e
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
