version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 2bf0d413-3c3b-4032-a6c6-3842ba4cc11f
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
