version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 23efbb8d-4eec-4950-bb72-e6ed99d929e1
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
