version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 429ec519-e268-4133-9543-32885509ad0d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
