version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 12c954e4-4da5-4795-a03f-f40acd9aa722
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
