version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: da417e6f-59af-48b7-aea0-b140baeefdc6
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
