version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 9a0c289d-e81c-4c51-8951-b460775f20f3
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
  variables:
    - io_openliberty_sample_testConfigOverwrite
      secret: io_openliberty_sample_testConfigOverwrite
