version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 9c8637a1-eff3-4e4d-b8e6-54d047ee7f59
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
