version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 3fecc665-6c18-4898-b055-e7c47f45ccf3
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
  variables:
    - name: io_openliberty_sample_testConfigOverwrite
      secret: io_openliberty_sample_testConfigOverwrite
