version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 2714a91b-7dd7-4284-a010-f72a406868ae
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
