version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 4762d12f-85d0-4979-8c78-ad9d0a00b2db
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
