version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: e133834a-cd65-4dda-b851-b5912fc02edd
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
