version: 1.0
app:
  instances: 
    min: 1
    max: 1
  version: 2e118cd1-3628-41cc-ad24-7f2f49fa4a99
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: testData
