version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: bc391608-f705-4a81-a33c-7a0df1e1ad9d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
