version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: aed15b29-8626-4d20-92b1-e28bbfee9650
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
