version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: "5ec0d1fb-dd4e-4589-85b3-f04af4bdd194"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
