version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: ca334196-f3bf-4131-8c4f-5ae246c8594d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
