version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 08901662-6b29-41a8-9e23-4a9ceefb55e5
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
